/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.defaultsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseCancelB();
		
		public void raiseValidateB();
		
		public void raiseNfcTrigger();
		
		public void raiseCoinTrigger();
		
		public void raiseAddCupB();
		
		public void raiseSugarTrigger();
		
		public void raiseSizeTrigger();
		
		public void raiseTemperatureTrigger();
		
		public void raiseSelectionTrigger();
		
		public void raiseClassicDrinkTrigger();
		
		public void raiseSoupTrigger();
		
		public void raiseIceTeaTrigger();
		
		public void raiseCoolingDone();
		
		public boolean isRaisedDoRefund();
		
		public boolean isRaisedDoReset();
		
		public boolean isRaisedDoWaterHeat();
		
		public boolean isRaisedDoCoffee();
		
		public boolean isRaisedDoExpresso();
		
		public boolean isRaisedDoTea();
		
		public boolean isRaisedDoSoup();
		
		public boolean isRaisedDoIceTea();
		
		public boolean isRaisedDoWaterFlow();
		
		public boolean isRaisedDoPutCup();
		
		public boolean isRaisedDoCheckNFC();
		
		public boolean isRaisedDoAddSugar();
		
		public boolean isRaisedDoAddSpices();
		
		public boolean isRaisedDoDecrement();
		
		public boolean isRaisedDoNotify();
		
		public boolean isRaisedSetClassicSliders();
		
		public boolean isRaisedSetSoupSliders();
		
		public boolean isRaisedSetIceTeaSliders();
		
		public boolean isRaisedDoCooling();
		
		public String getSelection();
		
		public void setSelection(String value);
		
		public long getSliderSugar();
		
		public void setSliderSugar(long value);
		
		public long getSliderSize();
		
		public void setSliderSize(long value);
		
		public long getSliderTemperature();
		
		public void setSliderTemperature(long value);
		
		public boolean getReady();
		
		public void setReady(boolean value);
		
	public List<SCInterfaceListener> getListeners();
		public void setSCInterfaceOperationCallback(SCInterfaceOperationCallback operationCallback);
	
	}
	
	public interface SCInterfaceListener {
	
		public void onDoRefundRaised();
		public void onDoResetRaised();
		public void onDoWaterHeatRaised();
		public void onDoCoffeeRaised();
		public void onDoExpressoRaised();
		public void onDoTeaRaised();
		public void onDoSoupRaised();
		public void onDoIceTeaRaised();
		public void onDoWaterFlowRaised();
		public void onDoPutCupRaised();
		public void onDoCheckNFCRaised();
		public void onDoAddSugarRaised();
		public void onDoAddSpicesRaised();
		public void onDoDecrementRaised();
		public void onDoNotifyRaised();
		public void onSetClassicSlidersRaised();
		public void onSetSoupSlidersRaised();
		public void onSetIceTeaSlidersRaised();
		public void onDoCoolingRaised();
		}
	
	public interface SCInterfaceOperationCallback {
	
		public String getSelection();
		
		public boolean isHot();
		
		public long getSugar();
		
		public long getSize();
		
		public long getTemperature();
		
		public boolean isPaid();
		
		public boolean isReady();
		
		public boolean isComplete();
		
		public boolean isDispo();
		
	}
	
	public SCInterface getSCInterface();
	
}
