/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.defaultsm;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseCancelB();
		
		public void raiseNfcTrigger();
		
		public void raiseCoinTrigger();
		
		public void raiseAddCupB();
		
		public boolean isRaisedDoRefund();
		
		public boolean isRaisedDoReset();
		
		public boolean isRaisedDoResetTimer();
		
		public boolean isRaisedDoWaterHeat();
		
		public boolean isRaisedDoCoffee();
		
		public boolean isRaisedDoExpresso();
		
		public boolean isRaisedDoTea();
		
		public boolean isRaisedReady();
		
		public String getSelection();
		
		public void setSelection(String value);
		
		public boolean getHotWater();
		
		public void setHotWater(boolean value);
		
		public boolean getEnoughtMoney();
		
		public void setEnoughtMoney(boolean value);
		
		public long getTime();
		
		public void setTime(long value);
		
		public boolean getIsHot();
		
		public void setIsHot(boolean value);
		
		public boolean getIsComplete();
		
		public void setIsComplete(boolean value);
		
		public boolean getIsInfused();
		
		public void setIsInfused(boolean value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoRefundRaised();
		public void onDoResetRaised();
		public void onDoResetTimerRaised();
		public void onDoWaterHeatRaised();
		public void onDoCoffeeRaised();
		public void onDoExpressoRaised();
		public void onDoTeaRaised();
		public void onReadyRaised();
		}
	
	public SCInterface getSCInterface();
	
}
