/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.2020.project.defaultsm;

import fr.univcotedazur.polytech.si4.fsm.2020.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.2020.project.ITimerCallback;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseCancelB();
		
		public void raiseNfcTrigger();
		
		public void raiseCoinTrigger();
		
		public void raiseAddCupB();
		
		public boolean isRaisedDoRefund();
		
		public boolean isRaisedDoReset();
		
		public boolean isRaisedDoResetTimer();
		
		public boolean isRaisedDoWaterHeat();
		
		public boolean isRaisedDoCoffee();
		
		public boolean isRaisedDoExpresso();
		
		public boolean isRaisedDoTea();
		
		public boolean isRaisedReady();
		
		public String getSelection();
		
		public void setSelection(String value);
		
		public boolean getHotWater();
		
		public void setHotWater(boolean value);
		
		public boolean getEnoughtMoney();
		
		public void setEnoughtMoney(boolean value);
		
		public long getTime();
		
		public void setTime(long value);
		
		public boolean getIsHot();
		
		public void setIsHot(boolean value);
		
		public boolean getIsComplete();
		
		public void setIsComplete(boolean value);
		
		public boolean getIsInfused();
		
		public void setIsInfused(boolean value);
		
	}
	
	public SCInterface getSCInterface();
	
}
